### ISSUE TITLE
Unable to find the Azure DevOps extension on the marketplace

### ISSUE THREAD

**Issue by tap1992** [deepcrawl/automator-sdk#80]
Hello!

I'm trying to install the [deepcrawl.automator-tools](https://marketplace.visualstudio.com/items?itemName=deepcrawl.automator-tools) but the link is dead, and searching for deepcrawl in the ADO extension marketplace doesn't find anything either.

![image](https://user-images.githubusercontent.com/75792610/209817412-e83555fa-33bf-4d1a-900e-8581f33fe6da.png)

Thanks

**Comment by anothersmith** [comment]
https://marketplace.visualstudio.com/items?itemName=deepcrawl.lumar-protect-tools

we have rebranded, I will make sure the links get updated

**Comment by frk-dc** [comment]
Hi @tap1992,
The Azure DevOps extension has been re-published as **Lumar Protect Tools** and can be installed from https://marketplace.visualstudio.com/items?itemName=deepcrawl.lumar-protect-tools
